-- =========================
-- TABLA USUARIO
-- =========================
CREATE TABLE USUARIO (
    DOCUMENTO_USUARIO NUMBER PRIMARY KEY,
    NOMBRE            VARCHAR2(100) NOT NULL,
    CORREO            VARCHAR2(100) UNIQUE NOT NULL,
    CELULAR           VARCHAR2(20) NOT NULL
);
-- =========================
-- TABLA USUARIOCONDUCTOR
-- =========================
CREATE TABLE USUARIOCONDUCTOR (
    DOCUMENTO_USUARIO NUMBER PRIMARY KEY,
    HABILITADO        CHAR(1) CHECK (HABILITADO IN ('0','1')),
    CONSTRAINT FK_USUARIOCONDUCTOR_USUARIO FOREIGN KEY (DOCUMENTO_USUARIO)
        REFERENCES USUARIO(DOCUMENTO_USUARIO)
);

-- =========================
-- TABLA VEHICULO
-- =========================
CREATE TABLE VEHICULO (
    PLACA              VARCHAR2(10) PRIMARY KEY,
    TIPO               VARCHAR2(50) NOT NULL,
    MODELO             VARCHAR2(50) NOT NULL,
    MARCA              VARCHAR2(50) NOT NULL,
    COLOR              VARCHAR2(30) NOT NULL,
    CIUDAD_EXPEDICION_PLACA  VARCHAR2(50) NOT NULL,
    CAPACIDAD_PASAJEROS NUMBER NOT NULL,
    DOCUMENTO_CONDUCTOR NUMBER NOT NULL,
    CONSTRAINT FK_VEHICULO_CONDUCTOR FOREIGN KEY (DOCUMENTO_CONDUCTOR)
        REFERENCES USUARIOCONDUCTOR(DOCUMENTO_USUARIO)
);

-- =========================
-- TABLA DISPONIBILIDAD
-- =========================
CREATE TABLE DISPONIBILIDAD (
    ID_DISPONIBILIDAD NUMBER PRIMARY KEY,
    DIA               NUMBER NOT NULL CHECK (DIA BETWEEN 1 AND 7),
    HORA_INICIO       TIMESTAMP NOT NULL,
    HORA_FIN          TIMESTAMP NOT NULL,
    PLACA_VEHICULO    VARCHAR2(10) NOT NULL,
    CONSTRAINT FK_DISPONIBILIDAD_VEHICULO FOREIGN KEY (PLACA_VEHICULO)
        REFERENCES VEHICULO(PLACA)
);

-- =========================
-- TABLA TARIFASERVICIO
-- =========================
CREATE TABLE TARIFASERVICIO (
    TIPO_SERVICIO VARCHAR2(50) PRIMARY KEY,
    COSTO_POR_KM  NUMBER(10,2) NOT NULL
);

-- =========================
-- TABLA SERVICIO
-- =========================
CREATE TABLE SERVICIO (
    ID_SERVICIO    NUMBER PRIMARY KEY,
    TIPO_SERVICIO  VARCHAR2(50) NOT NULL,
    CLIENTE_ID     NUMBER NOT NULL,
    CONDUCTOR_ID   NUMBER NOT NULL,
    ORIGEN_ID      NUMBER NOT NULL,
    DISTANCIA_KM   NUMBER NOT NULL,
    HORA_INICIO    TIMESTAMP NOT NULL,
    HORA_FIN       TIMESTAMP NOT NULL,
    DURACION_MIN   NUMBER NOT NULL,
    CONSTRAINT FK_SERVICIO_TARIFA FOREIGN KEY (TIPO_SERVICIO)
        REFERENCES TARIFASERVICIO(TIPO_SERVICIO),
    CONSTRAINT FK_SERVICIO_CLIENTE FOREIGN KEY (CLIENTE_ID)
        REFERENCES USUARIOSERVICIO(DOCUMENTO_USUARIO),
    CONSTRAINT FK_SERVICIO_CONDUCTOR FOREIGN KEY (CONDUCTOR_ID)
        REFERENCES USUARIOCONDUCTOR(DOCUMENTO_USUARIO),
    CONSTRAINT FK_SERVICIO_ORIGEN FOREIGN KEY (ORIGEN_ID)
        REFERENCES PUNTOGEOGRAFICO(ID_PUNTO_GEOGRAFICO)
);

-- =========================
-- TABLA SERVICIODISPONIBILIDAD
-- =========================
CREATE TABLE SERVICIODISPONIBILIDAD (
    ID_SERVICIO       NUMBER,
    ID_DISPONIBILIDAD NUMBER,
    PRIMARY KEY (ID_SERVICIO, ID_DISPONIBILIDAD),
    CONSTRAINT FK_SD_SERVICIO FOREIGN KEY (ID_SERVICIO)
        REFERENCES SERVICIO(ID_SERVICIO),
    CONSTRAINT FK_SD_DISP FOREIGN KEY (ID_DISPONIBILIDAD)
        REFERENCES DISPONIBILIDAD(ID_DISPONIBILIDAD)
);

-- =========================
-- TABLA PARADA
-- =========================
CREATE TABLE PARADA (
    ID_SERVICIO        NUMBER,
    ID_PUNTO_GEOGRAFICO NUMBER,
    NUMERO             NUMBER NOT NULL,
    PRIMARY KEY (ID_SERVICIO, ID_PUNTO_GEOGRAFICO),
    CONSTRAINT FK_PARADA_SERVICIO FOREIGN KEY (ID_SERVICIO)
        REFERENCES SERVICIO(ID_SERVICIO),
    CONSTRAINT FK_PARADA_PUNTO FOREIGN KEY (ID_PUNTO_GEOGRAFICO)
        REFERENCES PUNTOGEOGRAFICO(ID_PUNTO_GEOGRAFICO)
);

-- =========================
-- TABLA REVISION
-- =========================
CREATE TABLE REVISION (
    ID_REVISION   NUMBER PRIMARY KEY,
    EMISOR_ID     NUMBER NOT NULL,
    RECEPTOR_ID   NUMBER NOT NULL,
    CALIFICACION  NUMBER CHECK (CALIFICACION BETWEEN 0 AND 5),
    COMENTARIO    VARCHAR2(500) NOT NULL,
    CONSTRAINT FK_REVISION_EMISOR FOREIGN KEY (EMISOR_ID)
        REFERENCES USUARIO(DOCUMENTO_USUARIO),
    CONSTRAINT FK_REVISION_RECEPTOR FOREIGN KEY (RECEPTOR_ID)
        REFERENCES USUARIO(DOCUMENTO_USUARIO)
);

-- =========================
-- TABLA PUNTOGEOGRAFICO
-- =========================
CREATE TABLE PUNTOGEOGRAFICO (
    ID_PUNTO_GEOGRAFICO NUMBER PRIMARY KEY,
    NOMBRE              VARCHAR2(100),
    DIRECCION           VARCHAR2(200) NOT NULL,
    COORDENADAS         VARCHAR2(100) NOT NULL,
    CIUDAD              VARCHAR2(100) NOT NULL
);